packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  "next-auth": 5.0.0-beta.25

  # Dev tooling
  "@babel/preset-env": 7.26.9
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.2
  postcss: ^8.5.3
  vite-tsconfig-paths: 5.1.4

  # Testing
  '@playwright/test': 1.51.1

  # Misc
  zod: ^3.24.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0

  # React
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4

  # component-lib
  '@rn-primitives/accordion': 1.1.0
  '@rn-primitives/alert-dialog': 1.1.0
  '@rn-primitives/aspect-ratio': 1.1.0
  '@rn-primitives/avatar': 1.1.0
  '@rn-primitives/checkbox': 1.1.0
  '@rn-primitives/collapsible': 1.1.0
  '@rn-primitives/context-menu': 1.1.0
  '@rn-primitives/dialog': 1.1.0
  '@rn-primitives/dropdown-menu': 1.1.0
  '@rn-primitives/hover-card': 1.1.0
  '@rn-primitives/label': 1.1.0
  '@rn-primitives/menubar': 1.1.0
  '@rn-primitives/navigation-menu': 1.1.0
  '@rn-primitives/popover': 1.1.0
  '@rn-primitives/progress': 1.1.0
  '@rn-primitives/radio-group': 1.1.0
  '@rn-primitives/select': 1.1.0
  '@rn-primitives/separator': 1.1.0
  '@rn-primitives/slot': 1.1.0
  '@rn-primitives/switch': 1.1.0
  '@rn-primitives/table': 1.1.0
  '@rn-primitives/tabs': 1.1.0
  '@rn-primitives/toggle': 1.1.0
  '@rn-primitives/toggle-group': 1.1.0
  '@rn-primitives/tooltip': 1.1.0
  '@rn-primitives/types': 1.1.0

  '@tanstack/react-table': 8.11.7
  class-variance-authority: 0.7.0
  clsx: 2.1.1
  lucide-react: 0.483.0
  lucide-react-native: 0.454.0
  nativewind: 4.1.23
  react-native: 0.78.0
  react-native-reanimated: 3.17.1
  react-native-web: 0.19.13
  tailwind-merge: 2.5.4
  tailwindcss-animate: 1.0.7