openapi: 3.1.0
info:
  title: Chat App API
  version: 1.0.0
  description: API specification for the Chat application

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /signup:
    post:
      summary: Create a new user account
      description: Register a new user with email and password
      operationId: signup
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
          example: user@example.com
        password:
          type: string
          format: password
          minLength: 8
          description: User's password (min 8 characters)
          example: "mySecurePassword123"

    SignupResponse:
      type: object
      required:
        - id
        - email
        - created_at
        - updated_at
        - token
        - refresh_token
        - is_chirpy_red
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
          example: "123e4567-e89b-12d3-a456-426614174000"
        email:
          type: string
          format: email
          description: User's email address
          example: "user@example.com"
        created_at:
          type: string
          format: date-time
          description: Timestamp of when the user was created
          example: "2024-03-19T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp of when the user was last updated
          example: "2024-03-19T12:00:00Z"
        token:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        refresh_token:
          type: string
          description: Token used to obtain new access tokens
          example: "rt_123e4567e89b12d3a456426614174000"
        is_chirpy_red:
          type: boolean
          description: Indicates if the user has Chirpy Red status
          example: false

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message describing what went wrong
          example: "Invalid email format" 