/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Chat App API
 * API specification for the Chat application
 * OpenAPI spec version: 1.0.0
 */

export interface ErrorResponse {
  /** Error message describing what went wrong */
  error: string;
}
