/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Chat App API
 * API specification for the Chat application
 * OpenAPI spec version: 1.0.0
 */

export interface SignupRequest {
  /** User's email address */
  email: string;
  /**
   * User's password (min 8 characters)
   * @minLength 8
   */
  password: string;
}
