/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Chat App API
 * API specification for the Chat application
 * OpenAPI spec version: 1.0.0
 */

export interface SignupResponse {
  /** Unique identifier for the user */
  id: string;
  /** User's email address */
  email: string;
  /** Timestamp of when the user was created */
  created_at: string;
  /** Timestamp of when the user was last updated */
  updated_at: string;
  /** JWT access token */
  token: string;
  /** Token used to obtain new access tokens */
  refresh_token: string;
  /** Indicates if the user has Chirpy Red status */
  is_chirpy_red: boolean;
}
